# This is a basic workflow to help you get started with Actions

name: List AWS resources

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # Runs a set of commands using the runners shell
      - name: List Resources
        run: |
          echo "=============number of resources deployed in us-west-2 region=================="
          echo "number of buckets: $(aws s3 ls | wc -l)"
          echo "number of ebs volumes: $(aws ec2 describe-volumes --region us-west-2 --query 'length(Volumes[])')"
          echo "number of instances: $(aws ec2 describe-instances --region us-west-2 --query 'length(Reservations[].Instances[])')"
